<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGfc4qji\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGfc4qji/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGfc4qji.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGfc4qji\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGfc4qji\appProdProjectContainer([
    'container.build_hash' => 'Gfc4qji',
    'container.build_id' => '49d5e871',
    'container.build_time' => 1630917763,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGfc4qji');
