<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHa0lxao\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHa0lxao/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHa0lxao.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHa0lxao\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHa0lxao\appDevDebugProjectContainer([
    'container.build_hash' => 'Ha0lxao',
    'container.build_id' => 'baa0d880',
    'container.build_time' => 1630838106,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHa0lxao');
